### ISSUE TITLE
[feature] scrap informations(contents, press, title, journalist etc..) from article url

### ISSUE THREAD

**Issue by prodigy-sub** [prodigy-sub/snitch#14]
### Is your feature request related to a problem? Please describe.
...

### Describe the solution you'd like
...

### Describe alternatives you've considered
...

### TODOs
- [x] fetch html of the article
- [x] analyze the html structure of naver news
- [x] add a method in scraper.py

**add test codes**
- [x] add a sample html as a fixture
- [x] write unit test codes

**Comment by prodigy-sub** [comment]
article contents 의 경우, strings 같은 것으로 가져오면 사진의 설명까지 가져옴.
우선은 필요없은 정보라고 생각하여 제거함.
