### ISSUE TITLE
[feature] Add a simple API

### ISSUE THREAD

**Issue by prodigy-sub** [prodigy-sub/snitch#18]
### Is your feature request related to a problem? Please describe.
my very first API!

### Describe the solution you'd like
...

### Describe alternatives you've considered
...

### TODOs
**API**
- [x] FastAPI Overview
- [x] code
- [x] test

**DB**
- [x] create a Mongo DB Atlas account
- [x] cloud 에 DB setting
- [x] Mongo DB Overview
- [x] 연결 test 
- [x] model 구현
- [x] 적재 test

**Comment by prodigy-sub** [comment]
우선 아주아주 간단하게, 검색어로 request 보내면 스크래핑해서 response 로 기사 뱉어주는 방식 구현해보기

**Comment by prodigy-sub** [comment]
directory 구조도 우선은 다른 fastAPI 프로젝트들과 유사하게 가는 것이 좋을 것이라고 생각된다.
https://fastapi.tiangolo.com/tutorial/bigger-applications/

**Comment by prodigy-sub** [comment]
그냥 DB 에 넣는것 까지 한번에 하자.
PR 은 작게 유지하는게 좋겠지만 우선 빠르게 DB 까지 붙이는 편이 더 속도가 날 것 같다.

**Comment by prodigy-sub** [comment]
우선은 세세한 이해에 욕심부리지말고, api 라는게 어떻게 돌아가는지만 빠르게 이해하는 것에 집중하자.

**Comment by prodigy-sub** [comment]
**Model 구현**
- published date 는 datetime 으로 document 에 넣는 것이 좋은가? 어떤 것이 NoSQL 의 장점을 살리는 선택이지?
