### ISSUE TITLE
repo set up

### ISSUE THREAD

**Issue by prodigy-sub** [prodigy-sub/snitch#3]
### TODO
- [x] PR template 추가
- [x] test code 용 workflow 수정 및 다른 workflow 삭제 (inactivate)
- [x] branch 전략 정하기 -> github Flow (develop, feature)

### 하는 목적.
나중에 어떤 문제를 어떻게 풀었는지에 대한 기록을 남기기 위해
